version: 2
mergeable:
  - when: pull_request.*
    validate:
      - do: commit
        message:
            regex: '^(AB#[0-9]{1,})'
    pass: 
      - do: comment
        payload:
          body: >
            ###Successfully checked for Azure Work Item IDs in commits
            ####All commits in your PR have Azure Board Work Item IDs. Ready for Review!
            :+1 
      - do: labels
        add: 'Ready for Review'
    fail:
      - do: comment
        payload:
          body: >
            :warning
            ###Azure Boards Work Item IDs missing in commits
            <br>
            ####Some commits messages were found not having the Azure Boards Work Item ID (AB#1234).<br>
            ####We will close this PR for now.<br>
            ####To resolve, please do one of the following
            <ul>
              <li>Please identify your Azure Boards Work Item ID and <a href="https://gist.github.com/nepsilon/156387acf9e1e72d48fa35c4fabef0b4">amend your commits</a>, then start the PR again</li>
              <li>In case you do not have a Work Item ID to reference, please discuss with your reviewer(s) for alternate options</li>
            </ul> 
      - do: labels
        add: 'Non-Compliant'
      - do: close
      