name: simple-javascript-actions

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List files
        id: list-files
        run: |
          ls -a
          pwd
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo ${{ github.token }}
          
      - name: checkout
        id: checkout-files
        uses: actions/checkout@main
      - name: List files Post Checkout
        id: list-files-checkout
        run: |
          ls -a
          pwd
      - name: Simple JS Action
        id: greet
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: 'Mohan the Octocat'
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"
