# A GitHub action to find the number of inactive users in the organization
# and create an issue with the list of users.
name: Inactive Users
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
     
jobs:
  inactive-users:
    runs-on: ubuntu-latest
    steps:
      - name: Analyze User Activity
        id: analyze_user_activity
        uses: peter-murray/inactive-users-action@v1
        with:
          token: ${{ secrets.ORGANIZATION_AND_REPO_ACCESS_TOKEN }}
          organization: octodemo
          days: 30
      
      - name: Save User Activity Report
        uses: actions/upload-artifact@v2
        with:
          name: reports
          path: |
            ${{ steps.analyze_user_activity.outputs.report_csv }}